# Generated by Django 4.2.28 on 2026-02-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='concept',
            field=models.ForeignKey(blank=True, help_text='С каким понятием из онтологии связана эта задача (для адаптивного обучения)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='encyclopedia.concept', verbose_name='Понятие из онтологии'),
        ),
    ]
