# Generated by Django 5.2.10 on 2026-01-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text="URL-имя, например 'euclidean-dist'", unique=True)),
                ('description', models.TextField(verbose_name='Описание (HTML)')),
                ('difficulty', models.IntegerField(choices=[(1, '⭐ Novice (Основы)'), (2, '⭐⭐ Beginner (Логика)'), (3, '⭐⭐⭐ Intermediate (Алгоритмы)')], default=1)),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('function_name', models.CharField(help_text='Имя функции, которую должен написать юзер', max_length=100)),
                ('initial_code', models.TextField(verbose_name='Заготовка кода')),
                ('solution_code', models.TextField(verbose_name='Эталонное решение (для проверки)')),
                ('test_input', models.JSONField(default=dict, verbose_name='Входные данные теста')),
                ('expected_output', models.JSONField(default=dict, verbose_name='Ожидаемый ответ')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
