# Generated by Django 5.2.10 on 2026-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['algorithm', 'order']},
        ),
        migrations.AddField(
            model_name='task',
            name='algorithm',
            field=models.CharField(choices=[('kmeans', 'K-Means'), ('dbscan', 'DBSCAN'), ('hierarchical', 'Иерархическая кластеризация'), ('general', 'Общие знания')], default='general', max_length=50, verbose_name='Алгоритм'),
        ),
    ]
