# Generated by Django 5.2.10 on 2026-01-21 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_alter_task_options_task_algorithm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='function_name',
            field=models.CharField(help_text='Имя функции', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution_code',
            field=models.TextField(verbose_name='Эталонное решение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_input',
            field=models.JSONField(default=dict, verbose_name='Входные данные'),
        ),
        migrations.CreateModel(
            name='UserTaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код решения')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата попытки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='simulator.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка решения',
                'verbose_name_plural': 'Попытки решений',
                'ordering': ['-created_at'],
            },
        ),
    ]
