# Generated by Django 5.2.10 on 2026-01-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_alter_task_function_name_alter_task_solution_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название блока')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Блок задач',
                'verbose_name_plural': 'Блоки задач',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['category__order', 'order']},
        ),
        migrations.AlterField(
            model_name='task',
            name='algorithm',
            field=models.CharField(choices=[('kmeans', 'K-Means'), ('dbscan', 'DBSCAN'), ('hierarchical', 'Иерархическая кластеризация'), ('general', 'Общие знания')], default='general', max_length=50, verbose_name='Алгоритм (Тег)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='simulator.taskcategory', verbose_name='Блок (Категория)'),
        ),
    ]
