# Generated by Django 5.2.10 on 2026-01-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_taskcategory_alter_task_options_alter_task_algorithm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['algorithm', 'order']},
        ),
        migrations.AlterField(
            model_name='task',
            name='algorithm',
            field=models.CharField(choices=[('kmeans', 'K-Means'), ('dbscan', 'DBSCAN'), ('hierarchical', 'Иерархическая кластеризация'), ('general', 'Общие знания')], default='general', max_length=50, verbose_name='Алгоритм'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
    ]
