# Generated by Django 5.2.10 on 2026-01-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_remove_task_category_alter_task_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug (для URL)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Тег (Блок задач)',
                'verbose_name_plural': 'Теги задач',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['tags__order', 'order']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='algorithm',
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='simulator.tasktag', verbose_name='Тег (Блок)'),
        ),
    ]
