# Generated by Django 5.2.10 on 2026-01-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_tasktag_alter_task_options_remove_task_algorithm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('code', '💻 Написание кода'), ('choice', '📝 Выбор ответа (Тест)')], default='code', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_output',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ожидаемый ответ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='function_name',
            field=models.CharField(blank=True, help_text='Только для задач с кодом', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='initial_code',
            field=models.TextField(blank=True, verbose_name='Заготовка кода / Комментарий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution_code',
            field=models.TextField(blank=True, verbose_name='Эталонное решение / Пояснение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_input',
            field=models.JSONField(blank=True, default=dict, verbose_name='Входные данные / Варианты ответа'),
        ),
        migrations.AlterField(
            model_name='usertaskattempt',
            name='code',
            field=models.TextField(verbose_name='Код решения / Ответ пользователя'),
        ),
    ]
