# Generated by Django 5.2.10 on 2026-01-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_task_task_type_alter_task_expected_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, help_text='Позиция внутри тега (должна быть уникальной)', verbose_name='Порядок'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('tags', 'order'), name='unique_task_order_per_tag', violation_error_message='Задание с такой позицией уже существует в этом теге.'),
        ),
    ]
