# Generated by Django 5.2.10 on 2026-02-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0008_alter_task_order_task_unique_task_order_per_tag'),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskattempt',
            name='test_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attempts', to='testing.testattempt', verbose_name='Попытка теста (если в рамках теста)'),
        ),
    ]
