# Generated by Django 5.2.10 on 2026-01-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('simulator', '0008_alter_task_order_task_unique_task_order_per_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='К каким темам задач относится этот материал', related_name='materials', to='simulator.tasktag', verbose_name='Связанные темы'),
        ),
        migrations.AlterField(
            model_name='material',
            name='order',
            field=models.PositiveIntegerField(help_text='Уникальная позиция в списке материалов', unique=True, verbose_name='Порядок сортировки'),
        ),
    ]
