# Generated by Django 4.2.28 on 2026-02-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
        ('core', '0003_alter_material_tags_to_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='concept',
            field=models.ForeignKey(blank=True, help_text='Какое понятие из онтологии объясняет этот материал', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='encyclopedia.concept', verbose_name='Понятие из онтологии'),
        ),
    ]
