# Generated by Django 5.2.10 on 2026-01-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(help_text='Уникальный ID из OWL-онтологии', max_length=255, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание (Markdown)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Понятие',
                'verbose_name_plural': 'Понятия',
            },
        ),
        migrations.CreateModel(
            name='ConceptRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('IS_A', 'Является (Is A)'), ('PART_OF', 'Является частью'), ('USES', 'Использует'), ('DEPENDS', 'Зависит от (Пререквизит)'), ('RELATED', 'Связано с')], max_length=20, verbose_name='Тип связи')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_out', to='encyclopedia.concept', verbose_name='Откуда')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_in', to='encyclopedia.concept', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Семантическая связь',
                'verbose_name_plural': 'Связи',
                'unique_together': {('source', 'target', 'relation_type')},
            },
        ),
    ]
